export const type = {
  //SERV
  GET_SERVICES: "GET_SERVICES",
  GET_FAVS_SERVICES_DATA: "GET_FAVS_SERVICES_DATA",
  GET_GROUPS: "GET_GROUPS",
  POST_SERVICE: "POST_SERVICE",
  PUT_SERV_ID: "PUT_SERV_ID",
  DELETE_SERVICE: "DELETE_SERVICE",
  CREATE_SERVICE: "CREATE_SERVICE",
  POST_CATEGORY: "POST_CATEGORY",

  //USER
  POST_USER: "POST_USER",
  PUT_USER: "PUT_USER",
  GET_USER_INFO: "GET_USER_INFO",
  BANNED_USER: "BANNED_USER",
  //

  //PROVINCES
  GET_PROVINCES: "GET_PROVINCES",

  //FAVS
  GET_USER_FAVS: "GET_USER_FAVS",

  // Shopping
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  POST_PURCHASE: "POST_PURCHASE",

  //COOKIE
  SET_COOKIE: "SET_COOKIE",
};
