export const type = {
  //SERV
  GET_SERVICES: "GET_SERVICES",
  GET_FAVS_SERVICES_DATA: "GET_FAVS_SERVICES_DATA",
  GET_GROUPS: "GET_GROUPS",
  POST_SERVICE: "POST_SERVICE",
  PUT_SERV_ID: "PUT_SERV_ID",
  DELETE_SERVICE: "DELETE_SERVICE",
  CREATE_SERVICE: "CREATE_SERVICE",
  POST_CATEGORY: "POST_CATEGORY",
  SET_SERVICES_PAGE: "SET_SERVICES_PAGE",
  SET_END_PAGE: "SET_END_PAGE",


  POST_USER: 'POST_USER',
  PUT_USER: 'PUT_USER',
  GET_USER_INFO: 'GET_USER_INFO',
  BANNED_USER: 'BANNED_USER',
  FORGOT_PASSWORD : 'FORGOT_PASSWORD',
  RESET_PASSWORD : 'RESET_PASSWORD',

  //

  //PROVINCES
  GET_PROVINCES: "GET_PROVINCES",

  //FAVS
  GET_USER_FAVS: "GET_USER_FAVS",

  // Shopping
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  POST_PURCHASE: "POST_PURCHASE",
  SET_CART_STORAGE: "SET_CART_STORAGE",
  PAYPAL: "PAYPAL",
  SET_STATUS_ORDER: "SER_STATUS_ORDER",

  //COOKIE
  SET_COOKIE: "SET_COOKIE",

  // OBJ GLOBAL
  OBJ_GLOBAL: "OBJ_GLOBAL",

  //CHAT
  GET_CONVERTATIONS: "GET_CONVERTATIONS",
  POST_MESSAGE: "POST_MESSAGE",
  GET_POSTS: "GET_POSTS",
  CLEAR: "CLEAR",
  GET_CONTACTS_BOUGTH: "GET_CONTACTS_BOUGTH",
  GET_CONTACTS: "GET_CONTACTS",
  NEW_CONVERTATION: "NEW_CONVERTATION",

  //DARK
  PUT_DARK: "PUT_DARK",
};
