export const type = {
  //SERV
  GET_SERVICES: "GET_SERVICES",
  POST_SERVICE: "POST_SERVICE",
  PUT_SERV_ID: "PUT_SERV_ID",
  DELETE_SERVICE: "DELETE_SERVICE",
  CREATE_SERVICE:"CREATE_SERVICE",

  //USER
  POST_USER: "POST_USER",
  PUT_USER: "PUT_USER",
  GET_USERS: "GET_USERS",
  BANNED_USER: "BANNED_USER",
  //
  POST_PURCHASE: "POST_PURCHAS",
 
};

